config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
    resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  validates :message, presence: true, length: { maximum: 300, minimum: 3 }
 

  RATINGS = {
    "0stars.png": '0_stars',
    "1star.png":  '1_star',
    "2stars.png": '2_stars',
    "3stars.png": '3_stars',
    "4stars.png": '4_stars',
    "5stars.png": '5_stars' 
  }

  STARS = {
    "0 Stars": '0_stars',
    "1 Star":  '1_star',
    "2 Stars": '2_stars',
    "3 Stars": '3_stars',
    "4 Stars": '4_stars',
    "5 Stars": '5_stars' 
  }

  def rating_image
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end
  
  
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  belongs_to :user

  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode
  
  validates :name, presence: true, length: { minimum: 3, too_short: "Minimum %{count} characters required." }, uniqueness: { case_sensitive: false }
  validates :address, presence: true, length: { minimum: 3, too_short: "Minimum %{count} characters required." } 
  validates :description, presence: true, length: { minimum: 3, too_short: "Minimum %{count} characters required." } 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
  has_many :places
  has_many :comments
  has_many :photos
  
  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  } 

  def self.find_for_database_authentication(warden_conditions)
    user=where(["lower(username) = :value OR lower(email) = :value", { :value => warden_conditions.dup[:username].downcase }]).first   
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!


  def create
    @place = Place.find(params[:place_id])
    @comment = @place.comments.create(comment_params.merge(user: current_user))
    
    if @comment.invalid?
      flash[:error] = '<strong>Cannot save blank comment.</strong> &nbsp;&nbsp;Please try again.'
    end
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!


  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

   private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @places = Place.order("created_at ASC").page(params[:page]).per(5)
  end


  def new
    @place = Place.new
  end


  def create
    @place = current_user.places.create(place_params)
  
    if @place.valid?
       redirect_to places_path(@place)
    else
      render :new, status: :unprocessable_entity
    end

  end
  

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end


  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render file: Rails.root.join('public', 'not_found.html.erb'), status: :not_found
    end
  end


  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Access Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
       redirect_to place_path(@place)
    else
      render :edit, status: :unprocessable_entity
    end

  end


  def destroy
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Access Not Allowed', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end


  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meadster</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <%= link_to 'Meadster', root_path, class: 'navbar-brand' %>
    
    <ul class="navbar-nav offset-7">
      <% if user_signed_in? %>
        <div class="column">
          <div class="row">
        <li class="nav-item">
          <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li></div>
        <li class="add-place nav-item">
          <%= link_to new_place_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle"></i>
              Add A Meadery!
          <% end %>
        </li></div>
      <% else %>
        <div class="row">
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        </div>
      <% end %>
    </ul>
  </nav>

<% if notice.present? %>
<p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> Edit This Entry </h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-danger' %>

  <% end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>
  <div class="carousel-caption d-none d-md-block">
        <h3 class="title">California's Best Meaderies</h3>
      </div>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
       </div>
    <div class="carousel-item">
      <%= image_tag 'slider4.jpg', class: 'd-block img-fluid' %>
        </div>
    <div class="carousel-item">
      <%= image_tag 'slider5.jpg', class: 'd-block img-fluid' %>
   </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<%  @places.each do |place| %> 
<div class="booyah-box col-10 offset-1">
  <h1> <%= link_to place.name, place_path(place) %> </h1> 
  <i> <%= place.address %> </i> <br />
  <p> <%= place.description %> </p> 

  <% if place.user.present? %>
  <small>Added by: <%= place.user.username %></small>
  <% end %>

  <div>
    <% if place.comments.present? %>
    <div class="col-12">
      <blockquote>
        <% if place.comments.last.rating_image.present? %>
        <b><%= image_tag place.comments.last.rating_image %></b>
        <% end %>
        <%= place.comments.last.message %>
      </blockquote>
    </div>
    <% end %>
  
    <% if place.photos.present? %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <%= image_tag place.photos.first.picture %>
        <h5> <%= place.photos.first.caption %> </h5>
      </blockquote>
    </div>
    <% end %>
  </div>
</div>
<% end %>

<hr />
<%= paginate @places %>
<%= page_entries_info @places %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> Add a Meadery! </h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Add', class: 'btn btn-danger' %>

  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1 clearfix">

  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>


  <% if @place.latitude.present? && @place.longitude.present? %>

  <script>
    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSv6hssRC2NBp7IePvoynernJX1PS7Xyw&callback=initMap">
</script>

<div id="map"></div>

<% end %>

<br />

<div class="float-right">
  <% if current_user && current_user == @place.user %> 
  <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-secondary' %>
  <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
  <% end %>

</div>

</div>

<div class="clear"></div>

<div>
  <!-- Comments Modal -->
  <div class="modal fade" id="CommentsModal" tabindex="-1" role="dialog" aria-labelledby="CommentsModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="CommentsModalLabel">Add A Comment</h4>
        </div>
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::STARS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-danger' %>
        </div>
        <% end %>

      </div>
    </div>
  </div>

  <br />

  <div class="text-box col-11 clearfix">
    <h2 class="float-left">Comments</h2>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-secondary btn-md float-right" data-toggle="modal" data-target="#CommentsModal">
      Add A Comment
    </button>
  </div>

  <div class="row clearfix">
    <% @place.comments.each do |comment| %>
    <div class="columns col-12 col-sm-6">
      <blockquote>
        <% if comment.rating_image.present? %>
       <%= image_tag comment.rating_image %>
        <%= comment.message %>
        <% end %>
        <div>
        <small class="float-right"><i>Contributed by: <%= comment.user.username %></i></small>
        </div>
      </blockquote>
    </div>
    <% end %>
  </div>
</div>
<!--         -->
<div class="clear"></div>

<div>
  <!-- Photo Modal -->
  <div class="modal fade" id="PhotoModal" tabindex="-1" role="dialog" aria-labelledby="PhotoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="PhotoModalLabel">Add a Photo</h4>
        </div>
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :picture, label: false %>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>  
          <%= f.submit "Add a Photo", class: 'btn btn-danger' %>
        </div>
        <% end %>

      </div>
    </div>
  </div>

  <br />

  <div class="text-box clearfix">
    <h2 class="float-left">Photos</h2>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-secondary btn-md float-right" data-toggle="modal" data-target="#PhotoModal">
      Add A Photo
    </button>
  </div>

  <div class="clear"></div>

  <div class="row">
    <% @place.photos.each do |photo| %>
    <div class="columns col-12 col-sm-6">
      <blockquote>
        <%= image_tag photo.picture %>
        <h5> <%= photo.caption %> </h5>
        <div class="user-id">
          <small><i>Contributed by: <%= photo.user.username %></i></small>
        </div>
      </blockquote>
    </div>
    <% end %>
  </div>
</div>
<!--         -->

app/views/users/show.html.erb
<div class="user-booyah-box">
 <div class="row">
  <div class="col-3">
    <%= image_tag 'user.png' %>
  </div>

  <div class="col-9">
    <h1><%= @user.username %> / <%= @user.email %></h1>
    <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
    <h4><%= @user.comments.count %>  comments</h4>
    <h4><%= @user.comments.where(rating: '5_stars').count %>  5-star reviews</h4>
  </div>
  <div class="row col-4 offset-3">
    <a class="comments_anchor" href="#comments_added">Comments Added</a> 
    <a class="comments_anchor" href="#places_added">Places Added</a> 
  </div>
</div>
</div>
<div class="clear"></div>
</div>

<br />
<br />
<div class="user-booyah-box" id="comments_added">
  <h1 class="text-center" id="user-font">Comments Added</h1>
  <br />
  <br />
  <div class="row">
    <% @user.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.rating_image.present? %>
        <%= image_tag comment.rating_image %>  
        <% end %>
        <%= comment.message %>
      </blockquote>
    </div>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<br />
<div class="user-booyah-box" id="places_added">
  <h1 class="text-center" id="user-font">Places Added</h1>
  <br />
  <br />
  <div class="row">
    <% @user.places.each do |place| %>
    <div class="booyah-box col-10 offset-1">
      <h1><%= link_to place.name, place_path(place) %></h1><br />
      <i><%= place.address %></i><br />
      <p><%= place.description %></p><br />
      <% if place.comments.present? %>
      <div class="col-12">
        <blockquote>
          <% if place.comments.last.rating_image.present? %>
          <%= image_tag place.comments.last.rating_image %>  
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.username %></small>
        </blockquote>
      </div>
      <%end%>
    </div>
    <% end %>
  </div>